import type { NextPage } from "next";
import Head from "next/head";
import Header from "../shared/components/Header";
import { Normalize } from "styled-normalize";
import styled from "styled-components";
import Augl, { BigAugl, ListaAugl } from "../shared/components/Augl";
import Hero from "../shared/components/Hero/Hero";
import ContentImage from "../shared/components/ContentImage";
import Bitcoin from "../shared/components/Bitcoin/Bitcoin";
import { createGlobalStyle } from "styled-components";
import LargeImageWithText from "../shared/components/LargeImageWithText";

const GlobalStyle = createGlobalStyle`
  html {
    font-size: 10px;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;700&display=swap" rel="stylesheet"/>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      
      <Normalize />
      <GlobalStyle />
      <Main>
        <Header />
        <Augl />
        <Hero />
        <ContentImage />
        <Bitcoin />
        <ListaAugl />
        <LargeImageWithText />
        <BigAugl />
      </Main>
    </div>
  );
};

export default Home;

const Main = styled.main`
  padding: 0px 100px;
  max-width: 1600px;
  margin: auto;
  font-family: 'Poppins', sans-serif;
`;

